### PR TITLE
Feature/add search functionality

### PR DESCRIPTION
**Pull request by Ninad-Patil**
Have added the search functionality, please have a look at this PR @VanshKing30 for issue #85 
[searchfunctionality_.webm](https://github.com/VanshKing30/FoodiesWeb/assets/72431205/b8fc4b9e-d3f3-4bae-9b20-61f4b0f9b13f)

### CODE REVIEW

**Comment by VanshKing30** [comment]
Screenshot (6)
y

**Comment by VanshKing30** [comment]
Why is this happening ??

**Comment by Ninad-Patil** [comment]
image
Hi @VanshKing30  I am not able to reproduce the issue ,because it is showing like this only in my local

**Comment by Ninad-Patil** [comment]
[Visit Preview](https://vercel.live/open-feedback/foodies-web-app-hoqe-git-fork-ninad-pa-f55a27-vansh69s-projects.vercel.app?via=pr-comment-visit-preview-link&passThrough=1) 
This prevew from the vercel bot is also showing the changes

**Comment by VanshKing30** [comment]
Sorry !! brother your changes is completely disturbing the home page's ui ;)

**Pull request closed without merging**
