### PR TITLE
Added the Remember me button in authentication successfully

### LINKED ISSUE #302: Feat:  Add "Remember Me" Section for Authentication
### Describe the feature

The “Remember Me” feature for authentication is designed to improve user experience by reducing the frequency of login prompts. When a user selects “Remember Me” during login, the system stores a persistent cookie in the user’s browser. This cookie allows the system to recognize the user’s device and browser for a set period, typically ranging from several days to a few months.

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by codercake**
**This implementation includes:**
1. Centered "Forgot Password" link using flex justify-center.
2. "Remember Me" checkbox with appropriate HTML elements.

No new dependencies are required for these changes.

Fixes #302 

## Type of change

Please give a X on it which is applicable

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Refactor Code
- [ ] A documentation update
- [x] Others(mentioned in the issue number)

# How Has This Been Tested?

**Manual UI Inspection:**
1. Opened the application in a local development environment.
2. Navigated to the login page.
3. Visually inspected the layout to ensure the "Forgot Password" link is centered.
4. Verified that the "Remember Me" checkbox appears correctly and is functional.

**Checkbox Functionality Test:**
1. Checked the behavior of the "Remember Me" checkbox by selecting and deselecting it.
2. Verified that the checkbox's state is correctly tracked.

**Responsive Design Test:**
Resized the browser window to various dimensions to ensure the changes work well on different screen sizes, including mobile, tablet, and desktop.

# Screenshots and Videos:
Screenshot 2024-06-12 165322

# Checklist:
give a X on it which is applicable

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by codercake** [comment]
@VanshKing30 can you review the PR

**Comment by codercake** [comment]
@VanshKing30 can you review the PR?

**Comment by hustlerZzZ** [comment]
> @VanshKing30 can you review the PR?

Did you implement the backend logic as well?

**Comment by codercake** [comment]
> > @VanshKing30 can you review the PR?
> 
> Did you implement the backend logic as well?

yes. i did.

**Review by hustlerZzZ — APPROVED** [review]

**Pull request merged**
