### PR TITLE
gave every section the name

### PR DESCRIPTION
**Pull request by adityasingh-0803**
In the canteen card menu I have mentioned every section with name and change the size of it 

Fixes # (issue) #203 

## Type of change

Please give a X on it which is applicable

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [x] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:
give a X on it which is applicable

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by hustlerZzZ** [comment]
Can you attach a screen shot of the current UI

**Comment by adityasingh-0803** [comment]
im not able to view the page for ui

**Review by hustlerZzZ — APPROVED** [review]

**Comment by adityasingh-0803** [comment]
Thank you sir Please add gssoc label for which I can get points of it. @hustlerZzZ

**Comment by adityasingh-0803** [comment]
Please add the label @hustlerZzZ

**Comment by adityasingh-0803** [comment]
@hustlerZzZ assign the necessary labels so that leaderboard fetch points

**Pull request merged**
