### PR TITLE
Implement Email Verification Feature for User/Canteen Accounts

### LINKED ISSUE #9: Add Email Verification for Signup and Login
**Proposal: Implement Email Verification System**

### Objective:
Implement an email verification system for user registration and login processes to enhance security and user experience.

### Key Features:
- **Email Verification Upon Registration:** 
  - Upon registration, the system should automatically send a verification email to the user's provided email address.

- **Login Restriction:** 
  - Until the user verifies their email address, they should not be able to log in to the platform.

- **Notification for Unverified Accounts:**
  - Users attempting to log in without verifying their email address should receive a notification indicating their account is not verified.

- **Resend Verification Email:**
  - Users should have the option to request a new verification email if they haven't received it or have accidentally deleted it.
  - This resend functionality should be easily accessible from the login screen or through the user's account settings.

### Benefits:
- **Enhanced Security:**
  - Only users with verified email addresses can access their accounts, reducing the risk of unauthorized access.

- **Improved User Experience:**
  - Providing users with the option to request a new verification email reduces frustration in case of missed or lost emails.

By implementing this feature, we aim to significantly enhance the security of the platform while improving the overall user experience.

### PR DESCRIPTION
**Pull request by Slacky300**
### Description
This pull request introduces comprehensive email verification functionality for user accounts. Prior to this implementation, users could register without email verification. With this update, users are required to verify their email addresses upon registration before being able to log in. Additionally, options for resending verification emails and disabling email verification have been added, enhancing user control over their account security. Three new email templates have been included: one for requesting email verification and another for confirming successful email verification. Furthermore, a third email template notifies users if their verification token has expired. This feature greatly improves user communication and security throughout the verification process.

### Changes Made
- Implemented email verification feature, making it mandatory for user registration.
- Users are unable to log in until their email address is verified.
- Added resend verification email functionality.
- Added option to disable email verification via changes in the `.env` file.
- Included three email templates: one for requesting email verification, one for confirming successful email verification, and one for notifying users if their verification token has expired.
- Enhanced user control over account security.
- Utilized Gmail's SMTP server and nodemailer for sending emails.

### Testing
- Thoroughly tested email verification process, including registration, verification, resend functionality, and disabling.
- Ensured proper rendering of email templates.
- Verified integration with Gmail's SMTP server for sending emails.

### Additional Notes
- This feature significantly enhances user account security and ensures valid user contact information.
- Improves user experience with clear email communication throughout the verification process, including notification of token expiration.

### Screenshots

- Email Verification Email

Screenshot 2024-05-11 095317

- Successfully Verified 

Screenshot 2024-05-11 095339

- Token Expired

Screenshot 2024-05-11 100037

- Resend Verification Email Page

Screenshot 2024-05-11 100206

### Related Issues 
- Fixes #9

### CODE REVIEW

**Review by Slacky300 — COMMENTED** [review]
OK

**Comment by VanshKing30** [comment]
@Slacky300 Can you share your discord id !! I will accept this PR but i want to make some changes

**Comment by Slacky300** [comment]
> @Slacky300 Can you share your discord id !! I will accept this PR but i want to make some changes

@VanshKing30 here's my discord id: 824557192370716702

**Comment by VanshKing30** [comment]
Not this one 
eg : Vansh5238

**Comment by Slacky300** [comment]
> Not this one eg : Vansh5238

You mean username? then it's: rehman_khan_300

**Pull request closed without merging**
