### PR TITLE
Added Toastify Message 

### PR DESCRIPTION
**Pull request by sailaja-adapa**
Hello Project Admin
I added Toastify Message - Solved #330 

https://github.com/VanshKing30/FoodiesWeb/assets/161804629/b0fa236d-5d1c-4833-b4e6-d24a8c24f3dd

### CODE REVIEW

**Review by Adityajparmar37 — APPROVED** [review]

**Comment by Adityajparmar37** [comment]
good one

**Comment by sailaja-adapa** [comment]
@Adityajparmar37 Thank you ☺️

**Comment by sailaja-adapa** [comment]
@Adityajparmar37 Kindly Please Merge this PR

**Review by hustlerZzZ — APPROVED** [review]
Great work

**Comment by sailaja-adapa** [comment]
Thank you ☺️ @hustlerZzZ

**Pull request merged**
