### PR TITLE
Contact us frontend with email functionality

### PR DESCRIPTION
**Pull request by Isha1233**
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please give a X on it which is applicable

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**_Test A Describe here_**

**_Test B Describe here (if Requred)_**

# Screenshorts and Vedios:

give screenshorts and vedio of the changes you made

# Checklist:
give a X on it which is applicable

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Isha1233** [comment]
@VanshKing30 #249 is done

**Comment by Isha1233** [comment]
@VanshKing30 #250 is also done

**Review by Adityajparmar37 — CHANGES_REQUESTED** [review]
Add this constant in .env file . Do no kept it open .

image

**Comment by Isha1233** [comment]
> Add this constant in .env file . Do no kept it open .
> 
> image

Okhy I will update it

**Review by Adityajparmar37 — APPROVED** [review]

**Review by Adityajparmar37 — APPROVED** [review]

**Pull request merged**
