### PR TITLE
Feat:Error In Seeing Menu From User End #314

### PR DESCRIPTION
**Pull request by nishant0708**
Feat:Error In Seeing Menu From User End #314

In This Pr i have Solved 

https://github.com/VanshKing30/FoodiesWeb/assets/101548649/667871ba-393c-48f7-ab75-a0c071fb0639

**1)All these Bugs which were present In Main Branch**

**2) Removed HardCoded Url Values**
**3) Added env example file so new user can easily setup project in correct way**

**4) fixed image on menu card error (All the images were coming from unsplash and fixed issue when user have its own image)**

Screenshot 2024-06-16 024933 

**Here if user has its own Image then It will be showned inplace on random unsplashed Image**

image

**5) And Fixed Menu Not Showing Issue**

**6) Duplicate Code present in Signup and SignIn page** 
**7) Fixed Navbar  pages error**

Fixes # (issue)

## Type of change

Please give a X on it which is applicable

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**_Test A Describe here_**

**_Test B Describe here (if Requred)_**

# Screenshorts and Vedios:

give screenshorts and vedio of the changes you made

# Checklist:
give a X on it which is applicable

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
- [ x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @hustlerZzZ  In This I have Solved Multiple Issues in Project please assign it level accordingly

**Review by hustlerZzZ — APPROVED** [review]

**Comment by hustlerZzZ** [comment]
> hey @hustlerZzZ In This I have Solved Multiple(7-8 ) Issues in Project please assign it level accordingly

Can you mention them all

**Comment by nishant0708** [comment]
> > hey @hustlerZzZ In This I have Solved Multiple(7-8 ) Issues in Project please assign it level accordingly
> 
> Can you mention them all

I have mentioned them in pr description

**Comment by nishant0708** [comment]
> > > hey @hustlerZzZ In This I have Solved Multiple(7-8 ) Issues in Project please assign it level accordingly
> > 
> > 
> > Can you mention them all
> 
> I have mentioned them in pr description

**Comment by nishant0708** [comment]
Hey @hustlerZzZ Can you please Merge these branch because Without Changes present in this branch i can't start working on my other issue #320 #293  as it will create merge conflicts if started by solving them temporarily .I Hope you Get It ... as all of them are Linked Issues.

**Pull request merged**
