### PR TITLE
BUG:Feedback Submitted Notification Even though Feedback not given

### PR DESCRIPTION
**Pull request by panam1916**
Add condition before provide feedback before submit if feedback section is empty it get notification for provide feedback otherwise it show feedback submitted notification

### CODE REVIEW

**Comment by VanshKing30** [comment]
Good Work !!

**Comment by panam1916** [comment]
Now if you allow me to do work on backend part where canteen owner get feedback,i create issue for it

**Comment by panam1916** [comment]
can you aasign label for it?

**Comment by panam1916** [comment]
Can you please add labels for this ? Because i dont get points without label

**Comment by panam1916** [comment]
Hi Vansh Can you Please Assign label for this?

**Pull request merged**
