### PR TITLE
Feat: Google Auth Completed (Frontend + backend)

### PR DESCRIPTION
**Pull request by SaurabhS55**
At Frontend:
1. I have used react-oAuth library to authenticate gmail.
2. once auth completed, post request is made on respective route with attribute logintype="google".
3. On success, redirected to home page

At backend:
1. If request has logintype="google" then account created and success response sent to frontend.

Code work  well and all required functionalities are implemented. And don't forget to add your google client id in environment section of vercel with name REACT_APP_GOOGLE_CLIENT_ID="YOUR_ID"

### CODE REVIEW

**Comment by SaurabhS55** [comment]
Final view:-
image

**Comment by VanshKing30** [comment]
Got stuck here !

**Comment by SaurabhS55** [comment]
Screenshot is not visible
Could you upload it again

**Comment by VanshKing30** [comment]
Screenshot (7)

**Comment by SaurabhS55** [comment]
Ok, I got it.
Actually, To implement google authentication, we have to use google client id. And it is running on my system because I have my client id in my .env, but it is .gitignore. 
As discussed in first comment of PR, you just have to paste your google client id in environment section of vercel while deploying this build. REACT_APP_GOOGLE_CLIENT_ID="YOUR_ID"

To create your google client id you can follow this steps:
1. Open the Credentials page of the Google APIs console.
2. Create or select a Google APIs project. ...
3. Click Create credentials > OAuth client ID and for Application type select Web application to create a new client ID

Once you paste this- REACT_APP_GOOGLE_CLIENT_ID="YOUR_ID" in vercel environment section, it will work fine.

**Comment by SaurabhS55** [comment]
Hey @VanshKing30 Is this issue got resolved?

**Comment by VanshKing30** [comment]
This isnt working ~!

**Comment by ROKUMATE** [comment]
I am ready to work on this issue under the GSSOC label

**Comment by ROKUMATE** [comment]
i will use the app write package ...
If you want any other method to follow you can say so

**Pull request closed without merging**
