### PR TITLE
Default news card image added

### LINKED ISSUE #183: Feat: News Card default image
### Describe the feature

 There should be default image provided for news cards if the API does not supply any images

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by ANI2707**
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #183

## Type of change

Please give a X on it which is applicable

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**_Test A Describe here_**

**_Test B Describe here (if Req

# Screenshorts and Vedios:
Screenshot 2024-06-06 170032
ured)_**

# Checklist:
give a X on it which is applicable

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ANI2707** [comment]
@hustlerZzZ This pull request has been merged, but it's not showing on the leaderboard. Can you please assign labels to it?

**Comment by hustlerZzZ** [comment]
> @hustlerZzZ This pull request has been merged, but it's not showing on the leaderboard. Can you please assign labels to it?

ok lemme check

**Comment by ANI2707** [comment]
@hustlerZzZ Thanks bro..

**Comment by ANI2707** [comment]
@hustlerZzZ How long will it take for the leaderboard to be updated?

**Pull request merged**
