### PR TITLE
Home page UI improvemnet + add Home page data in separate navigation link 

### LINKED ISSUE #167: Feat: Home page UI improvemnet + add Home page data in separate navigation link
### Describe the feature

@VanshKing30  
We need to improve the home page UI by adding a carousel with images and moving the current list of hotel canteens to a separate page. This will enhance the visual appeal of the home page and make it more organized.
assign it to me under gssoc24

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by shivamgaur99**
Fixes #167 

## Type of change
1. add Canteen page for Canteen data earlier; it was on home page 
2. Adding background image in home page which give better look of website
3. add button in home page so user direct visit canteen

#tested responsiveness in both desktop and mobile view

Screenshorts:
image
image

image

### CODE REVIEW

**Comment by shivamgaur99** [comment]
@VanshKing30 please merge

**Comment by VanshKing30** [comment]
doubt
Where is the backgroun image ??

**Comment by shivamgaur99** [comment]
@VanshKing30 let me check

**Comment by shivamgaur99** [comment]
@VanshKing30 background image is added

**Comment by shivamgaur99** [comment]
@VanshKing30 if iisue has been resolved please merge it

**Comment by shivamgaur99** [comment]
@VanshKing30 will you tell me reason for closing pull request without merge?

**Pull request closed without merging**
