### PR TITLE
Updated Navbar.

### LINKED ISSUE #10: UI updation
Making the navbar responsive.
image

Small screens:
image
image

### PR DESCRIPTION
**Pull request by StephenStolk**
Fixes #10 

small screens:
image

- Responsive
- Animated using framer motion
- Preserved all actions

### CODE REVIEW

**Comment by VanshKing30** [comment]
Hi  @StephenStolk 

Could you please provide a screenshot of the changes you made to the resolved issue? Thanks!

**Comment by VanshKing30** [comment]
Thank you for your contribution! We appreciate your initiative in identifying and resolving the issue. Your efforts are invaluable to the project's success. Keep up the great work!

**Comment by StephenStolk** [comment]
The main deployment is not displaying the updated changes.
Please look into it as it is creating problem for identifying whether the
issue has been resolved or not.
Thank you

**Comment by VanshKing30** [comment]
@StephenStolk Can you please raise the PR one more time

**Comment by StephenStolk** [comment]
Created another pr.

Fixes #10

**Comment by StephenStolk** [comment]
Yes, it's done.

Fixes #10

**Pull request merged**
