### PR TITLE
Updated Navbar component

### LINKED ISSUE #10: UI updation
Making the navbar responsive.
image

Small screens:
image
image

### PR DESCRIPTION
**Pull request by StephenStolk**
[Re PR: ]
Fixes #10 
image

- Responsive navbar component
- Animated using Framer Motion
- Preserved all actions

### CODE REVIEW

**Comment by VanshKing30** [comment]
Still i dont know brother , why is this not getting deployed 
Can you please share your discord id ??

**Comment by StephenStolk** [comment]
It's asking for Authorization from me to get it deployed.

**Comment by VanshKing30** [comment]
Authorize it !!

**Comment by StephenStolk** [comment]
My discord id is: stephenstolk_18105

**Comment by StephenStolk** [comment]
I am getting this authorization:
image

**Comment by VanshKing30** [comment]
Approve it

**Pull request closed without merging**
