### PR TITLE
Fixed - #213 Sign up and sign in will work as well as loader added 

### LINKED ISSUE #213: BUG: SignUp and SignIn not working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am not able to create account.  It is showing failed to create account. I can fix this issue.
Please assign me this issue under GSSOC'24.
image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Adityajparmar37**
## Description 
Signup and Sign-in bug fixed . 
Problem was that somehow base API was commented out which is deployed API ( in frontend ) .
Still localhost/:4000 api was running. ( **I have commented out this API and uncommented BASE API** )

## **Extra**

**ADD LOADER** ,  so that user can known that ok it is doing some work in progress so that user will wait . 
Else it will continuously click the submit button and API fetching will load Up

## *PLEASE NOTE* :

There can be **_Formatting difference between your code and my code JUST DUE TO VSCODE setup_** No do not get that i have made so many changes

**JUST ADDED LOADER AS YOU HAVE DONE IN OTHER FILES**
**UNCOMMENT THE BASE URL**

# Screenshorts and Vedios:

## **PROBLEM VIDEO**

https://github.com/VanshKing30/FoodiesWeb/assets/105008414/c9392e80-d98e-4456-9f01-de0c42085379

## **FIXED IT - VIDEO**

**AFTER ADDING LOADER AND WITH PROPER  BASE API CALLING OF DEPLOYMENT FROM .ENV**

https://github.com/VanshKing30/FoodiesWeb/assets/105008414/64333339-5591-4483-8304-e26fe521ba57

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] Refactor Code

# Checklist:
give a X on it which is applicable

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Adityajparmar37** [comment]
Please check it out and if any problem comment me

**Comment by Adityajparmar37** [comment]
Please open vercel for PR so that the bot if on any PR change vercel will create a temp deployed website to check it . 
It will be helpful for you

**Comment by Adityajparmar37** [comment]
**PLEASE NOTE** :

**There can be _Formatting difference between your code and my code JUST DUE TO VSCODE setup_ No do not get that i have made so many changes** 

**JUST ADDED LOADER AS YOU HAVE DONE IN OTHER FILES**
**UNCOMMENT THE BASE URL**

**Comment by hustlerZzZ** [comment]
Everything is looking good... @Adityajparmar37

**Comment by Adityajparmar37** [comment]
please check it !

**Pull request merged**
